version: '3'
services:
  api:
    build:  
      context: ./gamesapi
      dockerfile: Dockerfile
    environment:
      - APIKEY=${APIKEY}
      - REDISURL=redis
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/storyteller`)"
      - "traefik.http.routers.api.entrypoints=web"
  gui:
    build:
      context: ./gamesui
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gui.entrypoints=web"
  redis:
    image: redis
    restart: always
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  